### ISSUE TITLE
Would you mind if I try updating and release that plugin to the public, along with some more features?

### ISSUE THREAD

**Issue by patsore** [YHDiamond/OpenTunnel#1]
question ^

**Comment by YHDiamond** [comment]
Feel free to make any PR, that would be greatly appreciated!

**Comment by patsore** [comment]
Oh yeah and is the server just straight up dead? It seems like the owner account was hacked and deleted

**Comment by patsore** [comment]
discord server, I mean

**Comment by YHDiamond** [comment]
That was my old discord account which was deleted because I made a request to the connections endpoint using my own token and discord wasn't a big fan of that lol. I have a new discord account but to be honest I totally forgot about this plugin when I made my new account 9 months ago so the plugin can have support through my main discord server for my other projects, https://discord.gg/ZcrmKTPfbt

**Comment by patsore** [comment]
thanks
